language: ruby
sudo: false
cache: bundler

rvm:
  - 2.7.4
  - 3.0.0

gemfile:
  - gemfiles/rails_6.1.gemfile

before_install:
- gem update --system --no-doc
- gem install bundler

notifications:
  email: false
